name: Android CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Restore keystore from base64
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ui/my-release-key.jks
    - name: Set up keystore properties
      run: |
        echo "MYAPP_RELEASE_STORE_FILE=my-release-key.jks" >> $GITHUB_ENV
        echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease \
          -PMYAPP_RELEASE_STORE_FILE=$MYAPP_RELEASE_STORE_FILE \
          -PMYAPP_RELEASE_KEY_ALIAS=$MYAPP_RELEASE_KEY_ALIAS \
          -PMYAPP_RELEASE_STORE_PASSWORD=$MYAPP_RELEASE_STORE_PASSWORD \
          -PMYAPP_RELEASE_KEY_PASSWORD=$MYAPP_RELEASE_KEY_PASSWORD
        # ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-android.apk
        path: ./**/*.apk

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: ./**/*.apk